apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-go2
  namespace: tsung
  labels: 
    app: hello-go2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-go2
  template:
    metadata:
      labels:
        app: hello-go2
      annotations:
        prometheus.io/scrape2: "true"
    spec:
      containers:
      - name: hello-go2
        image: a8uhnf/go:2.0
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 4
        ports:
        - name: hello
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: "go-svc2"
  namespace: tsung
spec:
  selector:
    app: "hello-go2"
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: ClusterIP


